quarkus:
  http:
    port: 3000
  rest-client:
    telegram-api:
      url: https://api.telegram.org
  default-locale: en
  locales:
    - en
    - ru
  log:
    console:
      json: false
      color: true
      format: "%d{HH:mm:ss} %-5p [%c{2.}] %s%e%n"

telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN}
  admin-chat-id: ${TELEGRAM_ADMIN_CHAT_ID}
  api-base-url: https://api.telegram.org
  webhook-secret: ${TELEGRAM_WEBHOOK_SECRET:}

app:
  mode: ${APP_MODE:polling}

"%prod":
  app:
    mode: webhook

"%dev":
  quarkus:
    devservices:
      enabled: false
  telegram:
    webhook-secret: ${TELEGRAM_WEBHOOK_SECRET:dummy-secret}
