quarkus.rest-client.baserow.url=https://api.baserow.io

baserow.events.events-table-id=824717
baserow.events.registrations-table-id=824726
baserow.events.guests-table-id=824727
baserow.events.notifications-table-id=831451

baserow.coworking.guests-table-id=824729
baserow.coworking.notifications-table-id=831434
baserow.coworking.tariffs-table-id=824730
baserow.coworking.active-tariffs-table-id=831438
baserow.coworking.meeting-room-bookings-table-id=824738
baserow.event.events-table-id=824717

baserow.token=${BASEROW_TOKEN:}

# Default (prod)
quarkus.log.category."org.jboss.resteasy.reactive.client".level=WARN
quarkus.log.category."io.quarkus.rest.client.reactive".level=WARN
quarkus.rest-client.logging.scope=none

# Enable JWT debug logging, add to application.properties
quarkus.log.category."io.smallrye.jwt".level=DEBUG
quarkus.log.category."io.quarkus.smallrye.jwt".level=DEBUG

# Dev profile only
%dev.quarkus.log.category."org.jboss.resteasy.reactive.client".level=DEBUG
%dev.quarkus.log.category."io.quarkus.rest.client.reactive".level=DEBUG
%dev.quarkus.rest-client.logging.scope=request-response
%dev.quarkus.rest-client.logging.body-limit=0

mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=lan-auth
quarkus.native.resources.includes=publicKey.pem
mp.jwt.verify.publickey=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlNBEIH1pqbB3w2tJy6YM2eNwFaG1NXqa9dZZsv33MV05Ex83gnkDmMkRb+8lEv39VdycOWyqpv2T7dCXycuJNN/LHiowALl8ckEx7J84dBrC6eOdRmk7FUHR0fsnVQMC7G32DTkHt+iEpGQK94LmpTUmqg2sSnDLnMYg14pkdQ8RFIMlkjytySHSbaibVnJCt71uBKxwvWoUrap5wkHusakx/roYw53TMPTZLMS503QW1o/XPpIhUjWTU1QskgwhNFcMBSXs17J1DDzXkabGj2ehmlcGAINbhg+6ATcgUVEtMc6EDjIqygvz5iWk4XkGucr57mrtjs3xu/LvlTaU2wIDAQAB