package com.lan.app.api.exception;

public enum ErrorCode {
    RESOURCE_NOT_FOUND,
    BUSINESS_CONFLICT,
    BASEROW_INCOMPLETE_ROW,
    BASEROW_UNAVAILABLE,
    INTERNAL_SERVER_ERROR,
    ROUTE_NOT_FOUND,
    UNAUTHORIZED,
    GUEST_NOT_FOUND,
    CHAT_ID_MISMATCH,
    TELEGRAM_CHAT_ID_CONFLICT,
}